### ISSUE TITLE
Question about benchmark data

### ISSUE THREAD

**Issue by zhouaik** [phdyang007/dlhsd#1]
How can you change the pgm fomat to excel file. And did you subtract the mean value of pixel or something else? I see some minus values in the table. Can you explain a bit about the feature extraction.

**Comment by phdyang007** [comment]
Layout images are, by nature, 2D or 3D matrices. There are a lot of packages in python like scipy, pillow can read images and generate corresponding matrices. As described in the paper http://appsrv.cse.cuhk.edu.hk/~hyyang/files/DAC17_CNN-HSD.pdf section III step1-step4,  I conduct DCT on consecutive 100x100 regions of each matrix. The csv benchmarks contain post-DCT contents, thats why there are negative values~ @zhouaik
