### ISSUE TITLE
Dataset label

### ISSUE THREAD

**Issue by slryou41** [phdyang007/dlhsd#4]
Hi, thanks for sharing your work and code. I have a question about the label of the dataset with gds format. Could you let me know which layer (or sample) corresponds to HS/NHS label? I can see layer number 10, 11, 12, 13, 21, 22, 23 from the train.gds file in the directory 1, but don't know how to map those samples to hotspot labels.

**Comment by phdyang007** [comment]
Pattern layer:  hotspot: 11, 12    non-hotspot: 13
Core region (ambit): hotspot:  21, 22   non-hotspot: 23
